// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Infrastructure.EntityFramework.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ContactosMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContactosMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201602021252438_ContactosMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
